[project]
name = "vm_aws"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12.8"
dependencies = [
    "pulumi>=3.165.0",
    "pulumi-aws>=6.78.0",
    "pulumi-tls>=5.2.0",
]
