version: "3.3"
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    ports:
      - 443:443
      - 80:80
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - VALIDATION=dns
      - DNSPLUGIN=duckdns
      - URL=dhzdhd.duckdns.org
      - SUBDOMAINS=wildcard
      - ONLY_SUBDOMAINS=true
    restart: unless-stopped
    volumes:
      - ./data/swag/config:/config

  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./data/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - swag
