services:
  traefik:
    container_name: traefik
    image: traefik:v3.7
    env_file:
      - env/traefik.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./data/traefik/logs:/var/log/traefik
      - ./data/traefik/middleware:/etc/traefik/middleware
      - ./data/traefik/letsencrypt:/letsencrypt
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true

  db_postgres:
    container_name: db_postgres
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - internal
    labels:
      - "traefik.enable=false"
    env_file:
      - env/database.env
    volumes:
      - db_postgres:/var/lib/postgresql/data
      - ./data/postgres:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    healthcheck:
      test: redis-cli ping || exit 1

  # backup:
  #   container_name: backup

  # Authentication
  authelia:
    container_name: authelia
    image: authelia/authelia:4.38
    user: 1000:1000
    networks:
      - proxy
      - internal
    environment:
      - TZ=Asia/Kolkata
    env_file:
      - env/authelia.env
    labels:
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"
    volumes:
      - ./data/authelia:/config
    restart: unless-stopped
    depends_on:
      db_postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Homepage
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    labels:
      - "traefik.http.routers.homepage.middlewares=authelia@file"
    networks:
      - proxy
    env_file:
      - .env
    volumes:
      - ./data/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock

  # Document archiver
  papra:
    container_name: papra
    image: ghcr.io/papra-hq/papra:latest-root
    labels:
      - "traefik.http.routers.papra.middlewares=authelia@file"
    networks:
      - proxy
    env_file:
      - .env
    volumes:
      - ./data/papra:/app/app-data
    restart: unless-stopped

  # Password manager
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    labels:
      - "traefik.http.routers.vaultwarden.middlewares=authelia@file"
    networks:
      - proxy
    env_file:
      - .env
    volumes:
      - ./data/vaultwarden:/data
    restart: unless-stopped

  # URL shortener
  kutt:
    container_name: kutt
    image: kutt/kutt:latest
    labels:
      - "traefik.http.routers.kutt.middlewares=authelia@file"
    environment:
      - DB_CLIENT=pg
      - DB_HOST=db_postgres
      - DB_PORT=5432
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - proxy
    env_file:
      - .env
    volumes:
      - ./data/kutt:/config
    restart: unless-stopped
    depends_on:
      db_postgres:
        condition: service_healthy
      redis:
        condition: service_started

  # File server with webdav support
  dufs:
    container_name: dufs
    image: sigoden/dufs:latest
    labels:
      - "traefik.http.routers.dufs.middlewares=authelia@file"
    environment:
      - DUFS_ALLOW_ALL=true
    networks:
      - proxy
    env_file:
      - .env
    volumes:
      - ./data/dufs:/data
    restart: unless-stopped

  # Media server
  immich:
    container_name: immich
    image: altran1502/immich-server:release
    labels:
      - "traefik.http.routers.immich.middlewares=authelia@file"
    environment:
      - TZ=Asia/Kolkata
    env_file:
      - env/immich.env
    networks:
      - proxy
    volumes:
      - ./data/immich/media:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - db_postgres
    restart: unless-stopped
    healthcheck:
      disable: false

  # Monitoring data source for grafana
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    networks:
      - proxy
    labels:
      - "traefik.http.routers.prometheus.middlewares=authelia@file"
    env_file:
      - .env
    volumes:
      - ./data/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-remote-write-receiver"
    restart: unless-stopped

  # Monitoring server metrics
  node_exporter:
    container_name: node_exporter
    image: quay.io/prometheus/node-exporter:latest
    labels:
      - "traefik.http.routers.node_exporter.middlewares=authelia@file"
    networks:
      - proxy
      - metrics
    command:
      - "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  # Monitoring docker metrics
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    labels:
      - "traefik.http.routers.cadvisor.middlewares=authelia@file"
    networks:
      - proxy
      - metrics
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    depends_on:
      - redis

  # Monitoring
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    networks:
      - proxy
    environment:
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel,grafana-simple-json-datasource
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    env_file:
      - .env
    labels:
      - "traefik.http.routers.grafana.middlewares=authelia@file"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning

    restart: unless-stopped

  # Monitoring log collection
  loki:
    container_name: loki
    image: grafana/loki:latest
    labels:
      - "traefik.http.routers.loki.middlewares=authelia@file"
    networks:
      - proxy
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./data/loki/:/etc/loki/
    restart: unless-stopped

  # Monitoring data collector
  alloy:
    container_name: alloy
    image: grafana/alloy:latest
    labels:
      - "traefik.http.routers.alloy.middlewares=authelia@file"
      - "traefik.http.routers.alloy.entrypoints=websecure"
      - "traefik.http.routers.alloy.tls=true"
      - "traefik.http.services.alloy.loadbalancer.server.port=12345"
    networks:
      - proxy
      - metrics
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    volumes:
      - ./data/alloy/:/etc/alloy/
      - ./data/authelia:/etc/alloy/authelia:ro
    restart: unless-stopped

volumes:
  db_postgres:
  db_mysql:
  grafana_data:
  prometheus_data:

networks:
  proxy:
    name: proxy
  internal:
    name: internal
    internal: true
  metrics:
    name: metrics
    internal: true
