services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - VALIDATION=dns
      - DNSPLUGIN=duckdns
      - URL=dhzdhd.duckdns.org
      - SUBDOMAINS=wildcard
      - ONLY_SUBDOMAINS=true
    volumes:
      - ./data/swag/config:/config

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./data/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - swag

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - ./data/calibre/config:/config
      - ./data/calibre/library:/books
    ports:
      - 8083:8083

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    environment:
      - name=value
    ports:
      - 8000:8000
      - 9443:9443
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:1.30.5
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - ROCKET_PORT=8080
      - DOMAIN=https://vaultwarden.dhzdhd.duckdns.org
    volumes:
      - ./data/vaultwarden:/data

  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: unless-stopped
    ports:
      - 9091:9091
    volumes:
      - ./data/authelia/config:/config

  postgres:
    image: postgres:16.2
    container_name: postgres
    restart: unless-stopped
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - ./data/postgres/.env
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.5
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - 5050:80
    env_file:
      - ./data/pgadmin/.env

volumes:
  portainer_data:
  postgres:
