services:
  db_postgres:
    container_name: db_postgres
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - env/database.env
    volumes:
      - db_postgres:/var/lib/postgresql/data
      - ./data/postgres:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1

  # Password manager
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    env_file:
      - .env
    volumes:
      - ./data/vaultwarden:/data
    ports:
      - 8080:8080
    restart: unless-stopped

  # URL shortener
  kutt:
    container_name: kutt
    image: kutt/kutt:latest
    environment:
      - DB_CLIENT=pg
      - DB_HOST=db_postgres
      - DB_PORT=5432
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    volumes:
      - ./data/kutt:/config
    ports:
      - 3001:3000
    restart: unless-stopped
    depends_on:
      db_postgres:
        condition: service_healthy
      redis:
        condition: service_started

  # File server with webdav support
  dufs:
    container_name: dufs
    image: sigoden/dufs:latest
    environment:
      - DUFS_ALLOW_ALL=true
    env_file:
      - .env
    volumes:
      - ./data/dufs:/data
    ports:
      - 5000:5000
    restart: unless-stopped

  # Media server
  immich:
    container_name: immich
    image: altran1502/immich-server:release
    environment:
      - TZ=Asia/Kolkata
    env_file:
      - env/immich.env
    volumes:
      - ./data/immich/media:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - db_postgres
    ports:
      - 2283:2283
    restart: unless-stopped
    healthcheck:
      disable: false

  # Monitoring data source for grafana
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    env_file:
      - .env
    volumes:
      - ./data/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    restart: unless-stopped

  # Monitoring server metrics
  node_exporter:
    container_name: node_exporter
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  # Monitoring docker metrics
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    depends_on:
      - redis

  # Monitoring dashboard visuals
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    env_file:
      - .env
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    restart: unless-stopped

volumes:
  db_postgres:
  db_mysql:
  grafana_data:
  prometheus_data:
