services:
  swag:
    container_name: swag
    image: lscr.io/linuxserver/swag:latest
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - VALIDATION=dns
      - SUBDOMAINS=wildcard
      - ONLY_SUBDOMAINS=true
    env_file:
      - .env
    volumes:
      - ./data/swag/config:/config

  database_postgres:
    container_name: database_postgres
    image: postgres:16
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    volumes:
      - database_postgres:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # database_mysql:
  #   container_name: database_mysql
  #   image: postgres:16
  #   environment:
  #     - PGDATA=/var/lib/postgresql/data/pgdata
  #   env_file:
  #     - .env
  #   volumes:
  #     - database_postgres:/var/lib/postgresql/data
  #   restart: unless-stopped

  cache:
    container_name: cache
    image: redis:alpine
    restart: unless-stopped

  # backup:
  #   container_name: backup

  # Authentication
  authelia:
    container_name: authelia
    image: authelia/authelia:4.38
    user: 1000:1000
    environment:
      - TZ=Asia/Kolkata
    env_file:
      - env/authelia.env
    volumes:
      - ./data/authelia:/config
    restart: unless-stopped

  # Password manager
  vaultwarden:
    container_name: vaultwarden
    image: ghcr.io/dani-garcia/vaultwarden:latest
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./data/vaultwarden:/data
    restart: unless-stopped

  # URL shortener
  kutt:
    container_name: kutt
    image: kutt/kutt:latest
    ports:
      - 8081:3000
    environment:
      - DB_CLIENT=pg
      - DB_HOST=database_postgres
      - DB_PORT=5432
      - REDIS_ENABLED=true
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    env_file:
      - .env
    volumes:
      - ./data/kutt:/config
    restart: unless-stopped
    depends_on:
      database_postgres:
        condition: service_healthy
      cache:
        condition: service_started

  # File server with webdav support
  dufs:
    container_name: dufs
    image: sigoden/dufs:latest
    ports:
      - 8082:5000
    environment:
      - DUFS_ALLOW_ALL=true
    env_file:
      - .env
    volumes:
      - ./data/dufs:/data
    restart: unless-stopped

volumes:
  database_postgres:
  database_mysql:
