services:
  traefik:
    container_name: traefik
    image: traefik:v3.7
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./data/traefik/logs:/var/log/traefik
      - ./data/traefik/middleware:/etc/traefik/middleware
      - ./data/traefik/letsencrypt:/letsencrypt
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true

  db_postgres:
    container_name: db_postgres
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - internal
    labels:
      - "traefik.enable=false"
    env_file:
      - .env
    volumes:
      - db_postgres:/var/lib/postgresql/data
      - ./data/postgres:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    healthcheck:
      test: redis-cli ping || exit 1

  # backup:
  #   container_name: backup

  # Authentication
  auth:
    container_name: authelia
    image: authelia/authelia:4.38
    user: 1000:1000
    networks:
      - proxy
      - internal
    environment:
      - TZ=Asia/Kolkata
      - X_AUTHELIA_CONFIG_FILTERS=template
    env_file:
      - .env
    labels:
      - "traefik.http.services.auth.loadbalancer.server.port=9091"
    volumes:
      - ./data/authelia:/config
    restart: unless-stopped
    depends_on:
      db_postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Homepage
  home:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    labels:
      - "traefik.http.routers.home.middlewares=authelia@file"
    networks:
      - proxy
    env_file:
      - .env
    volumes:
      - ./data/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock

  # Document archiver
  doc:
    container_name: papra
    image: ghcr.io/papra-hq/papra:latest-root
    labels:
      - "traefik.http.routers.doc.middlewares=authelia@file"
    networks:
      - proxy
    env_file:
      - .env
    volumes:
      - ./data/papra:/app/app-data
    restart: unless-stopped

  # Password manager
  vault:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    labels:
      - "traefik.http.routers.vault.middlewares=authelia@file"
    networks:
      - proxy
    environment:
      - DOMAIN=${VAULTWARDEN_DOMAIN}
      - ROCKET_PORT=${VAULTWARDEN_ROCKET_PORT}
      - SIGNUPS_ALLOWED=${VAULTWARDEN_SIGNUPS_ALLOWED}
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - SSO_ENABLED=${VAULTWARDEN_SSO_ENABLED}
      - SSO_ONLY=${VAULTWARDEN_SSO_ONLY}
      - SSO_CLIENT_ID=${VAULTWARDEN_SSO_CLIENT_ID}
      - SSO_CLIENT_SECRET=${VAULTWARDEN_SSO_CLIENT_SECRET}
      - SSO_AUTHORITY=${VAULTWARDEN_SSO_AUTHORITY}
      - SSO_SCOPES=${VAULTWARDEN_SSO_SCOPES}
      - SSO_SIGNUPS_MATCH_EMAIL=${VAULTWARDEN_SSO_SIGNUPS_MATCH_EMAIL}
    env_file:
      - .env
    volumes:
      - ./data/vaultwarden:/data
    restart: unless-stopped

  # URL shortener
  link:
    container_name: kutt
    image: kutt/kutt:latest
    labels:
      - "traefik.http.routers.link.middlewares=authelia@file"
    environment:
      - DB_CLIENT=pg
      - DB_HOST=db_postgres
      - DB_PORT=5432
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_PASSWORD=${KUTT_DB_PASSWORD}
      - DB_NAME=${KUTT_DB_NAME}
      - DB_USER=${KUTT_DB_USER}
      - JWT_SECRET=${KUTT_JWT_SECRET}
    networks:
      - proxy
    env_file:
      - .env
    volumes:
      - ./data/kutt:/config
    restart: unless-stopped
    depends_on:
      db_postgres:
        condition: service_healthy
      redis:
        condition: service_started

  # File server with webdav support
  fs:
    container_name: dufs
    image: sigoden/dufs:latest
    labels:
      - "traefik.http.routers.fs.middlewares=authelia@file,dufs-csp@file"
      - "traefik.http.services.fs.loadbalancer.server.port=5000"
    command: /data --allow-all
    networks:
      - proxy
    env_file:
      - .env
    volumes:
      - ./data/dufs:/data
    restart: unless-stopped

  # Media server
  media:
    container_name: immich
    image: altran1502/immich-server:release
    labels:
      - "traefik.http.routers.media.middlewares=authelia@file"
    environment:
      - TZ=Asia/Kolkata
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
      - DB_USERNAME=${IMMICH_DB_USERNAME}
      - DB_DATABASE_NAME=${IMMICH_DB_DATABASE_NAME}
      - DB_HOSTNAME=${IMMICH_DB_HOSTNAME}
    env_file:
      - .env
    networks:
      - proxy
    volumes:
      - ./data/immich/media:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - db_postgres
    restart: unless-stopped
    healthcheck:
      disable: false

  # Monitoring data source for grafana
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    networks:
      - proxy
    labels:
      - "traefik.http.routers.prometheus.middlewares=authelia@file"
    env_file:
      - .env
    volumes:
      - ./data/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-remote-write-receiver"
    restart: unless-stopped

  # Monitoring server metrics
  node_exporter:
    container_name: node_exporter
    image: quay.io/prometheus/node-exporter:latest
    networks:
      - metrics
    command:
      - "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  # Monitoring docker metrics
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    networks:
      - metrics
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    depends_on:
      - redis

  # Monitoring
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    networks:
      - proxy
    env_file:
      - .env
    labels:
      - "traefik.http.routers.grafana.middlewares=authelia@file"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning

    restart: unless-stopped

  # Monitoring log collection
  loki:
    container_name: loki
    image: grafana/loki:latest
    labels:
      - "traefik.http.routers.loki.middlewares=authelia@file"
    networks:
      - proxy
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./data/loki/:/etc/loki/
    restart: unless-stopped

  # Monitoring data collector
  alloy:
    container_name: alloy
    image: grafana/alloy:latest
    labels:
      - "traefik.http.routers.alloy.middlewares=authelia@file"
      - "traefik.http.routers.alloy.entrypoints=websecure"
      - "traefik.http.routers.alloy.tls=true"
      - "traefik.http.services.alloy.loadbalancer.server.port=12345"
    networks:
      - proxy
      - metrics
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    volumes:
      - ./data/alloy/:/etc/alloy/
      - ./data/authelia:/etc/alloy/authelia:ro
    restart: unless-stopped

volumes:
  db_postgres:
  db_mysql:
  grafana_data:
  prometheus_data:

networks:
  proxy:
    name: proxy
  internal:
    name: internal
    internal: true
  metrics:
    name: metrics
    internal: true
