services:
  swag:
    container_name: swag
    image: lscr.io/linuxserver/swag:latest
    restart: unless-stopped
    ports:
      - 443:443
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - VALIDATION=dns
      - SUBDOMAINS=wildcard
      - ONLY_SUBDOMAINS=true
    env_file:
      - .env
    volumes:
      - ./data/swag/config:/config

  database:
    container_name: database
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data
    restart: unless-stopped

  backup:
    container_name: backup

  vaultwarden:
    container_name: vaultwarden
    image: ghcr.io/dani-garcia/vaultwarden:latest
    ports:
      - 8080:8080
    environment:
      - ROCKET_PORT=8080
    env_file:
      - .env
    volumes:
      - ./data/vaultwarden:/data
    restart: unless-stopped

volumes:
  database: