---
- name: Set up infra
  hosts: server

  pre_tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages
      become: true
      ansible.builtin.apt:
        upgrade: dist

  roles:
    - role: geerlingguy.docker
      become: true

  vars_files:
    - ../vars/env.yml
    - ../vars/files.yml

  tasks:
    - name: Clone repository (https://danwin1210.de/github-ipv6-proxy.php)
      ansible.builtin.git:
        repo: "https://www.github.com/dhzdhd/desktop-server"
        dest: "server"

    - name: Create directories
      ansible.builtin.file:
        path: "/home/{{ username }}/server/{{ item | dirname }}"
        state: directory
      loop: "{{ files | map(attribute='dest') }}"

    - name: Copy files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "/home/{{ username }}/server/{{ item.dest }}"
      loop: "{{ files }}"

    # Do not follow docker docs
    # https://github.com/nextcloud/all-in-one/blob/main/docker-ipv6-support.md
    - name: Setup IPv6 in docker
      become: true
      ansible.builtin.copy:
        src: "../../../daemon.json"
        dest: "/etc/docker/daemon.json"

    - name: Restart docker
      become: true
      ansible.builtin.systemd:
        name: docker
        state: restarted

    - name: Run docker compose
      become: true
      community.docker.docker_compose_v2:
        project_src: "/home/{{ username }}/server"
