---
- name: Set up infra
  hosts: server

  roles:
    - role: geerlingguy.docker
      become: true

  tasks:
    - name: Clone repository
      ansible.builtin.git:
        repo: "https://github.com/dhzdhd/desktop-server"
        dest: "server"
